uncategorized:
  related_links: '<a href="example.com">example.com</a>|<a href="example.org">example.org</a>'

required:
  title:
    default: 'Rigidoj'
  site_description:
    default: ''
  contact_email:
    default: ''
    type: email
  notification_email:
    default: 'info@unconfigured.example.com'
    type: email
  site_contact_username:
    default: ''
    type: username
  logo_url:
    default: '/new/defaults/default-logo.png'
  digest_logo_url:
    default: ''
  mobile_logo_url:
    default: ''
  favicon_url:
    default: '/new/defaults/default-favicon.ico'
  apple_touch_icon_url: '/new/defaults/default-apple-touch-icon.png'

basic:
  default_locale:
    default: 'en'
    refresh: true
  ga_universal_tracking_code:
    default: ''
    regex: "^UA-\\d+-\\d+$"
  ga_universal_domain_name:
    default: 'auto'

judger:
  judger_platform:
    default: 'C|C++|Java'
  solution_status: 'Judging|Network error|Judge error|Accepted|Wrong answer|Time limit exceeded|Memory limit exceeded|Presentation error|Runtime error|Compile error|Output limit exceeded'
  solution_color: '#aaaaaa|#bbbbbb|#eeeeee|#009933|red|blue|#990099|#333333|#FF6600|#3366FF|purple'

user:
  allow_update_username:
    default: false
  allow_update_name:
    default: true
